name: NodeJS with Nx

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node Packages
        run: |
          npm install

      - name: Run Lint Frontend
        run: |
          npx nx run frontend:lint

      - name: Build Frontend
        run: |
          npx nx run frontend:build

      - name: Run Frontend Test
        run: |
          npx nx run frontend:test
